server:
  port: 9000
  servlet:
    context-path: /hideAndSeekService
spring:
  profiles:
    active: local
  application:
    name: hide-and-seek-service
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: XFaCOEF93UIOsbUgp7kkjh4kdroN/fikkeI9sU+iJh36k/gG/zAefBfY+sianakjN6WY/1784N8aHPEqjhcGHeHsV6WptgbYUyA+RalIqXCR98wOhQIE9GvsmE9C78ilBwyMGQQB9c8fJzvh2j/+h1SXxM3sRjvWU/dYZOsq8V8fLF4ZpjSbbDQqYDzgWAvDue7FdqHpA99dpDLD/42ctQ==)
    username: ENC(tT+1yTTWeJOpyXvfzHKRZQ==)
    password: ENC(X+YEjQTIgkPdRflrTTDT2A==)
  redis:
    host: localhost
    password: ENC(X+YEjQTIgkPdRflrTTDT2A==)
    connect-timeout: 5000
  cloud:
    nacos:
      server-addr: ENC(RGfZB8esYiYdH92veXgodjtt1DIvGjSI)
      username: ENC(f3mztE8HuMm6J7XuOncSBQ==)
      password: ENC(f3mztE8HuMm6J7XuOncSBQ==)
  servlet:
    multipart:
      max-file-size: 1GB # 单个文件大小为5MB
      max-request-size: 5GB # 总上传的数据大小5MB
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: HIDE-AND-SEEK # 加密秘钥
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
jwt:
  ALLOW_INVALID_TOKEN_SEARCH_NUM: 2 # 无效的tokenId最多允许查询mysql的次数
  INVALID_EXPIRE: 10 # 无效的tokenId在redis中的缓存时长，单位：分钟